# Generated by Django 5.0.2 on 2025-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество (граммы)')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('min_threshold', models.PositiveIntegerField(verbose_name='Минимальный порог (граммы)')),
            ],
        ),
    ]
