name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: kindegarden_test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" -utestuser -ptestpassword; then
              break
            fi
            sleep 2
          done

      - name: Set environment variables
        run: |
          echo "DATABASE_NAME=kindegarden_test" >> $GITHUB_ENV
          echo "DATABASE_USER=testuser" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=testpassword" >> $GITHUB_ENV
          echo "DATABASE_HOST=127.0.0.1" >> $GITHUB_ENV

      - name: Run migrations
        run: python manage.py migrate

      - name: Test app
        run: python manage.py test