name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-d
      - name: Run migrations
        run: python manage.py migrate
      - name: Test app
        run: python manage.py test